name 'solr_simple'
maintainer 'Michael Haas'
maintainer_email 'hmi@linux.com'
license 'apachev2'
description 'Installs/Configures solr_simple'
long_description 'Installs/Configures solr_simple'
version '0.1.0'
depends 'libarchive', '~> 0.5.0'
depends 'apt', '~> 2.7.0'
depends 'java', '~> 1.31.0'
